.gitignore
.rubocop.yml
Gemfile
exe/rspec_n
lib/rspec_n.rb
lib/rspec_n/formatters/table_formatter.rb
lib/rspec_n/helpers/time_helpers.rb
lib/rspec_n/run.rb
lib/rspec_n/runner.rb
lib/rspec_n/version.rb
rspec_n.gemspec

PR for issue #1

---

CHANGELOG.md
exe/rspec_n
lib/rspec_n.rb
lib/rspec_n/constants.rb
lib/rspec_n/errors.rb
lib/rspec_n/errors/bad_argument.rb
lib/rspec_n/errors/bad_option.rb
lib/rspec_n/formatters/table_formatter.rb
lib/rspec_n/helpers/core_ext/array.rb
lib/rspec_n/helpers/core_ext/string.rb
lib/rspec_n/input.rb
lib/rspec_n/run.rb
lib/rspec_n/runner.rb
rspec_n.gemspec

PR for issue #4

---

CHANGELOG.md
exe/rspec_n
lib/rspec_n/formatters/table_formatter.rb
lib/rspec_n/input.rb
lib/rspec_n/run.rb
lib/rspec_n/runner.rb

PR for issue #6

---

CHANGELOG.md
exe/rspec_n
lib/rspec_n.rb
lib/rspec_n/formatters/file_formatter.rb
lib/rspec_n/input.rb
lib/rspec_n/runner.rb

PR for issue #5

---

CHANGELOG.md

PR for issue #15

---

CHANGELOG.md
lib/rspec_n/formatters/table_formatter.rb
lib/rspec_n/helpers/core_ext/string.rb
lib/rspec_n/run.rb

PR for issue #19

---

CHANGELOG.md
lib/rspec_n/formatters/table_formatter.rb
lib/rspec_n/run.rb
lib/rspec_n/runner.rb

PR for issue #23

---

CHANGELOG.md
lib/rspec_n/formatters/file_formatter.rb
lib/rspec_n/runner.rb

PR for issue #26

---

CHANGELOG.md
lib/rspec_n/version.rb

PR for issue #28

---

CHANGELOG.md
exe/rspec_n

PR for issue #30

---

CHANGELOG.md
lib/rspec_n/version.rb

PR for issue #33

---

.rubocop.yml
.travis.yml
CHANGELOG.md
Gemfile
rspec_n.gemspec

[PR for issue #41] Remove default ruby

---

.travis.yml

[PR for issue #39] Update travis.yml

---

CHANGELOG.md
rspec_n.gemspec

[PR for issue #43] Use pry 0.12.x

---

.travis.yml

[PR for issue #39] Remove unneeded rubies from travis

---

CHANGELOG.md
lib/rspec_n/input.rb

[PR for issue #38] Improve '--order rand' addition

---

CHANGELOG.md
README.md
lib/rspec_n/version.rb

[PR for issue #46] Prepare release 1.2.2

---

CHANGELOG.md
lib/rspec_n/input.rb

[PR for issue #49] Make '--order project' work

---

Gemfile

[PR for issue #50] Prepare 1.3.0 release

---

CHANGELOG.md

[PR for issue #55] Add CHANGELOG info

---

CHANGELOG.md

[PR for issue #57] Redesign the CHANGELOG

---

.rubocop.yml
lib/rspec_n.rb
lib/rspec_n/constants.rb
lib/rspec_n/runner.rb

[PR for issue #50] Fix rubocop issues

---

CHANGELOG.md
rspec_n.gemspec
spec/rspec_n_spec.rb

[PR for issue #61] Add rubocop_plus ~> 1.0

---

CHANGELOG.md
rspec_n.gemspec

[PR for #64] Use pry ~> 0.13.0

---

.travis.yml
CHANGELOG.md

[PR for #66] Update .travis.yml ruby & bundler versions

---

.rubocop.yml
.travis.yml
CHANGELOG.md
rspec_n.gemspec

[PR for #68] Make Ruby 2.5 the min supported version

---

README.md

[PR for #68] Update min supported Ruby version in README

---

CHANGELOG.md
rspec_n.gemspec

[PR for #73] Use rake ~> 13.0

---

CHANGELOG.md

[PR for #71] Make CHANGELOG.md use lists

---

CHANGELOG.md

[PR for #78] Require Pathname

---

.rubocop.yml
.travis.yml
CHANGELOG.md
README.md
rspec_n.gemspec

[PR for #68] Set Ruby 2.6 as the min supported Ruby version

---

CHANGELOG.md
rspec_n.gemspec

[PR for #64] Use pry ~> 0.14.0

---

.travis.yml

[PR for #66] Use bundler 2.2.17

---

CHANGELOG.md
rspec_n.gemspec

[PR for #83] Use rubocop_plus ~> 2.0

---

Rakefile
lib/rspec_n/errors/bad_option.rb
lib/rspec_n/formatters/table_formatter.rb
lib/rspec_n/helpers/core_ext/string.rb
lib/rspec_n/input.rb

[PR for #71] Fix rubocop issues

---

.rubocop.yml
CHANGELOG.md
Gemfile
LICENSE.md
README.md
Rakefile
bin/console
exe/rspec_n
rspec_n.gemspec

[PR for #89] Cleanup docs and fix rubocop issues

---

.github/workflows/check_pull_request.yml

[PR for #87] Run RuboCop check in parallel

---

exe/rspec_n
lib/rspec_n/helpers/arguments_helper.rb
rspec_n.gemspec
spec/rspec_n_spec.rb

[#95] Fix RuboCop issues

---

.github/workflows/check_pull_request.yml
CHANGELOG.md
README.md

[#97] Add Ruby 3.1 support

---

README.md

[#95] Polish the README

---

CHANGELOG.md
lib/rspec_n/version.rb

[#95] Prepare 1.5.0 release

---

CHANGELOG.md

[#102] Add note to CHANGELOG

---

CHANGELOG.md
rspec_n.gemspec

[PR for #105] Use colorize ~> 1.1.0

---

Gemfile
lib/rspec_n/runner.rb
rspec_n.gemspec

Fix RuboCop issues

---

.github/workflows/check_pull_request.yml
.rubocop.yml
CHANGELOG.md
README.md
rspec_n.gemspec

Remove Ruby 2.7 support

---

.github/pull_request_template.md
CHANGELOG.md

Add PR template

---

.github/workflows/check_pull_request.yml
CHANGELOG.md

Add Ruby 3.2 support

---

.github/workflows/check_pull_request.yml
CHANGELOG.md

Add Ruby 3.3 support

---

CHANGELOG.md
lib/rspec_n/version.rb

Prepare 1.6.0 release

---

CHANGELOG.md
README.md
lib/rspec_n/constants.rb

Use db:schema:load to prepare databases

---

CHANGELOG.md
README.md
lib/rspec_n/version.rb

Prepare 2.0.0 release

---

CHANGELOG.md
Gemfile

Update dev and test gems
